-- Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The
-- first ten pentagonal numbers are:

-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
-- difference, 70 22 = 48, is not pentagonal.

-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum
-- and difference is pentagonal and D = |Pk - Pj| is minimised; what
-- is the value of D?

module Euler044 where

isPentagonal :: Integral a => a -> Bool
isPentagonal n = p && (root + 1) `mod` 6 == 0
  where (p, root) = isPerfect (24 * n + 1)
        isPerfect m = (r * r == m, r)
          where r = floor . sqrt $ fromIntegral m
                
pentagonalNum :: Integral a => a -> a
pentagonalNum n = n * (3 * n - 1) `div` 2

isWanted :: [Int] -> Int
isWanted l
  | r == [] = isWanted (next:l)
  | otherwise = snd $ head r
  where r = filter (\(x, y) -> isPentagonal x && isPentagonal y) $ zip (map (next +) l) (map (next-) l)
        next = pentagonalNum len
        len = 1 + length l

result044 = isWanted []
