-- Triangle, pentagonal, and hexagonal numbers are generated by the
-- following formulae:

-- Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
-- Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
-- Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...

-- It can be verified that T285 = P165 = H143 = 40755.

-- Find the next triangle number that is also pentagonal and
-- hexagonal.

module Euler where

common :: Ord a => [a] -> [a] -> [a]
common a@(x:xs) b@(y:ys)
  | x == y = x : common xs ys
  | x > y = common a ys
  | otherwise = common xs b

t = map (\n -> n * (n + 1) `div` 2) [1..]
p = map (\n -> n * (3 * n - 1) `div` 2) [1..]
h = map (\n -> n * (2 * n - 1)) [1..]

searchNext :: (Ord a, Num a) => [a] -> a
searchNext (x:xs)
  | x > 40755 = x
  | otherwise = searchNext xs

result045 = searchNext . common h $ common t p
